config/routes.rb
Isleep::Application.routes.draw do
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  devise_for :users do
    get '/users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session # :new_user_session
    delete '/users/logout' => 'devise/sessions#destroy', :as => :user_logout
  end
  
  resources :users
  resources :checkins

  root :to => 'checkins#index'
  

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  PROVIDERS = [:facebook]

  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.create_by_omniauth(hash, current_user = nil)
    hash = ActiveSupport::HashWithIndifferentAccess.new hash
    auth = find_from_hash(hash)
    unless auth
      current_user ||= User.create_from_auth!(hash)
      auth = Authorization.new(:user=>current_user,:uid=>hash[:uid],:provider=>hash[:provider])
      auth.save
    end
    auth
  end

  private

  def self.find_from_hash(hash)
    if hash[:provider] && hash[:uid]
      find_by_provider_and_uid(hash[:provider],hash[:uid])
    end
  end

end

app/models/checkin.rb
# encoding: utf-8
class Checkin < ActiveRecord::Base
  TYPES = { :sleep => '要睡覺', :wakeup => '剛起床' }
  TYPE_COLLECTION = TYPES.map
  
  belongs_to :user
  validates_presence_of :user_id
  validates_presence_of :check_type
  validates_presence_of :date
  validates_inclusion_of :check_type, :in => TYPES.keys.concat(TYPES.keys.map(&:to_s))

  before_validation :sync_date
  
  serialize :point_log, Hash
  
  def point_log
    ActiveSupport::HashWithIndifferentAccess.new super
  end
  
  def self.human_attribute_name(attr, opts = {})
    attr.to_sym == :check_type ? '' : super
  end
  
  def time
    created_at.strftime("%k:%M")
  end
  
  private 
  
  def sync_date
    self.date = created_at.present? ? created_at.to_date : Date.today if new_record?
  end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :authorizations
  has_many :checkins, :order => 'created_at DESC'

  def self.create_from_auth!(hash)
    created_hash = {:email => hash[:user_info][:email], :name => hash[:user_info][:name] }
    user = (created_hash[:email].nil? ? nil : User.find_by_email(created_hash[:email])) || User.new(created_hash)
    if user.email
      user.confirm!
    elsif user
      user.save!
    end
    user
  end

  def next_check_type
    if ck = checkins.first
      return Checkin::TYPES.keys[ (Checkin::TYPES.keys.index(ck.check_type.to_sym) + 1) % 2 ]
    end
    :wakeup
  end
  
  def render_sleep_target
    sleep_target.strftime("%k:%M") if sleep_target
  end
  
  def render_wakeup_target
    wakeup_target.strftime("%k:%M") if wakeup_target
  end

  def facebook_id
    authorizations.where(:provider => :facebook).first.uid
  end
  
  def avatar_url
    "http://graph.facebook.com/" + facebook_id + "/picture?type=large"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def after_sign_in_path_for(user)
    request.env['omniauth.origin'] || checkins_path
  end

  def after_sign_out_path_for(user)
    checkins_path
  end
  
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @checkins = current_user.checkins
    render :index
  end
  
  def create
    @checkin = current_user.checkins.build params[:checkin]
    if @checkin.save
      redirect_to checkins_path
    else
      flash[:error] = @checkin.errors.full_messages.first
      send :index
    end
  end
  
  def destroy
    @checkin = current_user.checkins.find params[:id]
    @checkin.destroy
    redirect_to request.referer.to_s
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @auth = Authorization.create_by_omniauth(auth_hash, current_user)
    if @auth.user
       sign_in_and_redirect :user, @auth.user
    else
      raise do
        logger.info "auth_hash: #{auth_hash.inspect}"
        logger.info "@auth: #{@auth.errors.inspect}"
        redirect_to new_user_session_path
      end
    end
  end

  def failure
    flash[:error] = params[:message]
    redirect_to new_user_session_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @user = current_user
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = User.find current_user.id
    if @user.update_attributes params[:user]
      redirect_to checkins_path
    end
  end
  
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  
  def bt_login
    link_to "Facebook 登入", '/auth/facebook', :class => 'btn btn-primary'
  end
  
  def checkin_type_select(f, options = {})
    strs = []
    value = params[:check_type] || current_user.next_check_type
    Checkin::TYPES.each do |k,v|
      v += " "+content_tag(:span, "目標 #{options[:user].send("render_#{k}_target")}", :class => :label) if options[:user] && options[:user].respond_to?("#{k}_target") && options[:user].send("#{k}_target")
      str = content_tag :label, :class => :radio do
        opts = { :name => "#{f.object_name}[check_type]", :value => k, :type => :radio }
        opts[:checked] = :yes if k.to_sym == value.to_sym
        raw [tag(:input, opts), v].join
      end
      strs << str
    end
    raw strs.join("\n")
  end
  
  def code_font(text, opts = {})
    raw content_tag(:code, text)
  end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
  
  def checkins_dates(checkins)
    return [] if checkins.size == 0
    values = checkins.map(&:date)
    (values.min..values.max).map(&:to_s).reverse
  end
  
  def checkins_pick(checkins, opts = {})
    checkins.select{ |ck| ck.date.to_s == opts[:date].to_s && ck.check_type.to_sym == opts[:check_type].to_sym }
  end
  
  def checkins_pick_time(checkins, opts = {})
    ck = checkins.select{ |ck| ck.date.to_s == opts[:date].to_s && ck.check_type.to_sym == opts[:check_type].to_sym }.first || Checkin.new
    ck.created_at ? ck.created_at.strftime("%k:%M") : nil
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def level(value)
    lv_exp(value)[0]
  end
  
  def current_exp(value)
    return 0 if value <= 0
    value % 100
  end
  
  def max_exp(value)
    lv_exp(value)[1]
  end
  
  private 
  
  def lv_exp(value)
    lv = 0
    base = 10
    return [1, base] if value <= 0
    exp = base
    while value >= exp
      lv += 1
      exp = exp + (lv * base)
    end
    [lv + 1, exp]
  end
  
end

app/views/application/_bar.html.haml
.progress.progress-striped.active{ :class => local_assigns[:value_type].to_s == 'hp' ? "progress-danger" : ''}
  .bar{ :style => "width: #{current_exp(value)*100/max_exp(value)}%"}

app/views/application/_exp_help_hp.html.haml
%h5="HP 計算方式"
%ul
  %li
    - if current_user
      = link_to "設定", edit_user_path(current_user)
    - else
      = '設定'
    =" 你的目標起床時間"
  %li
    =raw "於目標起床時間前 #{code_font(HP_BIAS_EARLY)} 小時以及目標起床時間後 #{code_font HP_BIAS_LATE} 小時(彈性)進行起床打卡, 即可得 #{code_font HP_MAX_INCREASE} 點經驗值, 假設起床時間定於早上 7 點, 則 7 點半以前打卡即可獲得經驗值"
  %li
    =raw "於目標起床時間後 #{code_font HP_BIAS_LATE} 小時以後打卡時, 以 #{code_font '30'} 分鐘為單位, 每晚 30 分鐘則扣 #{code_font '1'} 點經驗值, 最多不扣超過 #{code_font HP_MAX_DECREASE.abs} 點經驗值, 例如 7 點的目標起床時間, 若於 9 點打卡則會扣 3 點經驗值"

app/views/application/_exp_help_sp.html.haml
%h5="SP 計算方式"
%ul
  %li
    - if current_user
      = link_to "設定", edit_user_path(current_user)
    - else
      = '設定'
    =" 你的目標睡覺時間"
  %li
    =raw "於目標睡覺時間前 #{code_font(SP_BIAS_EARLY)} 小時以及後 #{code_font SP_BIAS_LATE} 小時內進行睡覺打卡, 即可得 #{code_font SP_MAX_INCREASE} 點經驗值, 假設睡覺時間定於晚上 11  點, 則於 #{11-SP_BIAS_EARLY} ~ #{11+SP_BIAS_LATE} 點間打卡即可獲得經驗值"
  %li
    =raw "於上述範圍以外時間打卡睡覺時, 以 #{code_font '30'} 分鐘為單位, 差距時間內每 30 分鐘則扣 #{code_font '1'} 點經驗值, 最多不扣超過 #{code_font SP_MAX_DECREASE.abs} 點經驗值, 例如 23  點的睡覺時間, 若於凌晨 1 點打卡則會扣 2  點經驗值"

app/views/application/_falshes.html.haml
- flash.each do |k, v|
  .alert{ :class => "alert-#{k}" }
    %button.close{ :data => { :dismiss => :alert } }
    = v

app/views/application/_head.html.haml
.topbar.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{ :data => { :toggle => :collapse, :target => '.nav-collapse' } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "愛睡覺+_+", root_path, :class => :brand
      .nav-collapse.collapse
        %ul.nav
          - if user_signed_in?
            - c = { params[:check_type].to_s.to_sym => :active }
            - Checkin::TYPES.each do |type_value, type_name|
              %li{ :class => c[type_value] }
                =link_to type_name, checkins_path(:check_type => type_value)
            %li{ :class => params[:action] == 'show' && params[:controller] == 'users' ? :active : '' }
              =link_to current_user.name, user_path(current_user)
        %ul.nav.pull-right
          - if user_signed_in?
            %li
              = link_to "設定", edit_user_path(current_user)
            %li
              = link_to "登出", user_logout_path, :method => :delete, :confirm => "請確定"
          - else
            %li
              = link_to 'Facebook登入', '/auth/facebook'

app/views/application/_point.html.haml
- name = name.to_s
- bt_classes = { 'hp' => 'btn-danger', 'sp' => 'btn-primary' }
%a.btn{ :data => { :toggle => :modal }, :href => "##{name}", :class => bt_classes[name] }
  = "#{name.upcase} #{value.nil? ? '' : value}"
.modal.hide{ :id => name }
  .modal-header
    %button.close{ :data => { :dismiss => :modal } }='x'
    %h2
      = name.upcase
  .modal-body
    %h4
      - if value
        = "等級:"
        %span.badge.badge-inverse=level(value)
        ="經驗值: "
        %span.badge.badge-warning=value
        =" / "
        %span.badge.badge-success=max_exp(value)
    %p
    - if value
      = render :partial => 'bar', :locals => { :value => value, :value_type => name }
    = render :partial => "exp_help_#{name}"

app/views/checkins/_checkin.html.haml
.checkin{ :data => { :type => :hover, :show => '.close' }}
  %span= checkin.time
  = link_to 'x', checkin_path(checkin), :method => :delete, :confirm => '請確定', :class => "close"

app/views/checkins/_form.html.haml
= simple_form_for Checkin.new, :method => :post, :url => checkins_path, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    .control-group
      %label.control-label="經驗值"
      .controls
        - [:hp, :sp].each do |p|
          = render :partial => 'point', :locals => { :value => current_user.send(p), :name => p }
    .control-group
      %label.control-label="目前狀態"
      .controls= checkin_type_select f, :user => current_user
    .control-group
      %label.control-label="(現在)時間"
      .controls= f.input_field :created_at, :class => 'input-mini'
    .control-group
      .controls= f.submit "打卡記錄", :class => 'btn-large'
      

app/views/checkins/index.html.haml
.row-fluid
  .span10
    = render :partial => 'form'
    
  .span10
    %table.table.table-striped
      %tr
        %th="日期"
        - Checkin::TYPES.each do |k, v|
          %th=v
      - checkins_dates(@checkins).each do |date|
        %tr
          %td=date
          - Checkin::TYPES.each do |k, v|
            %td
              - checkins_pick(@checkins, :date => date, :check_type => k).reverse.each do |ck|
                = render :partial => 'checkin', :object => ck

app/views/layouts/application.html.haml
!!! 5
:plain
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
  <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
  <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
  <!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=edge,chrome=1")
    %meta(name="viewport" content="width=device-width,initial-scale=1")
    %title iSleep
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
  .head
    = render :partial => "head"
  .container
    .top_fix.visible-desktop
    = render :partial => "falshes"
    = yield
  %foot
    = render :partial => "foot"

app/views/users/edit.html.haml
= simple_form_for @user, :url => user_path(@user), :method => :put, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    .control-group
      %label.control-label="目標睡覺時間"
      .controls= f.input_field :sleep_target, :class => 'input-mini', :include_blank => true
    .control-group
      %label.control-label="目標起床時間"
      .controls= f.input_field :wakeup_target, :class => 'input-mini', :include_blank => true
    .control-group
      .controls= f.submit "儲存", :class => 'btn-large'  
  

app/views/users/show.html.haml
%h1=@user.name
%ul.thumbnails
  %li
    .thumbnail
      = image_tag @user.avatar_url

.row
  %h3.span1="HP"
  .value.span6
    %b.span1="#{@user.hp} / #{max_exp(@user.hp)}"
    .span2= render :partial => 'bar', :locals => { :value_type => :hp, :value => @user.hp }
    %b.span1="Level #{level(@user.hp)}"
    .clearfix


.row
  %h3.span1="SP"
  .value.span6
    %b.span1="#{@user.sp} / #{max_exp(@user.sp)}"
    .span2= render :partial => 'bar', :locals => { :value => @user.sp }
    %b.span1="Level #{level(@user.sp)}"
    .clearfix